<script lang="ts" setup>
import { reactive } from 'vue';
import LogItem from './LogItem.vue';
const state = reactive<{
    logList: Array<any>;
}>({
    logList: [
        { "level": 30, "time": 1667135852866, "pid": 162117, "hostname": "xVan-PC", "context": "RouterExplorer", "msg": "Mapped {/, GET} route" },
        { "level": 50, "time": 1667133146744, "pid": 157999, "hostname": "xVan-PC", "req": { "id": 1, "method": "GET", "url": "/", "query": {}, "params": { "0": "" }, "headers": { "host": "127.0.0.1:3000", "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "accept-language": "en-US,en;q=0.5", "accept-encoding": "gzip, deflate, br", "connection": "keep-alive", "upgrade-insecure-requests": "1", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "if-none-match": "W/\"d-ZtXAnUlm/qTktXBCao4AU261gec\"" }, "remoteAddress": "::ffff:127.0.0.1", "remotePort": 60872, "body": {} }, "err": { "type": "Error", "message": "Test Error", "stack": "Error: Test Error\n    at AppService.getHello (/workspace/Dev/temp/nest_log/src/app.service.ts:7:18)\n    at AppController.getHello (/workspace/Dev/temp/nest_log/src/app.controller.ts:12:28)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:15:53\n    at Observable._subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable._trySubscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:245:19)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:235:18\n    at Object.errorContext (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n    at Observable.subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:221:5)" }, "msg": "Test Error" },
        { "level": 50, "time": 1667133320018, "pid": 157999, "hostname": "xVan-PC", "req": { "id": 2, "method": "GET", "url": "/", "query": {}, "params": { "0": "" }, "headers": { "host": "127.0.0.1:3000", "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "accept-language": "en-US,en;q=0.5", "accept-encoding": "gzip, deflate, br", "dnt": "1", "connection": "keep-alive", "upgrade-insecure-requests": "1", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "cross-site", "pragma": "no-cache", "cache-control": "no-cache" }, "remoteAddress": "::ffff:127.0.0.1", "remotePort": 41966, "body": {} }, "err": { "type": "Error", "message": "Test Error", "stack": "Error: Test Error\n    at AppService.getHello (/workspace/Dev/temp/nest_log/src/app.service.ts:7:18)\n    at AppController.getHello (/workspace/Dev/temp/nest_log/src/app.controller.ts:12:28)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:15:53\n    at Observable._subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable._trySubscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:245:19)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:235:18\n    at Object.errorContext (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n    at Observable.subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:221:5)" }, "msg": "Test Error" },
        { "level": 50, "time": 1667135795535, "pid": 161859, "hostname": "xVan-PC", "req": { "id": 1, "method": "GET", "url": "/", "query": {}, "params": { "0": "" }, "headers": { "host": "127.0.0.1:3000", "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "accept-language": "en-US,en;q=0.5", "accept-encoding": "gzip, deflate, br", "connection": "keep-alive", "upgrade-insecure-requests": "1", "sec-fetch-dest": "document", "sec-fetch-mode": "navigate", "sec-fetch-site": "none", "sec-fetch-user": "?1", "if-none-match": "W/\"d-ZtXAnUlm/qTktXBCao4AU261gec\"" }, "remoteAddress": "::ffff:127.0.0.1", "remotePort": 59772, "body": {} }, "err": { "type": "Error", "message": "Test Error", "stack": "Error: Test Error\n    at AppService.getHello (/workspace/Dev/temp/nest_log/src/app.service.ts:7:18)\n    at AppController.getHello (/workspace/Dev/temp/nest_log/src/app.controller.ts:12:28)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/router/router-execution-context.js:38:29\n    at InterceptorsConsumer.transformDeferred (/workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:31:33)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/@nestjs+core@9.1.6_bx3wiubfryfbvpzqwr6ml4ajpu/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:15:53\n    at Observable._subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/observable/defer.ts:55:15)\n    at Observable._trySubscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:245:19)\n    at /workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:235:18\n    at Object.errorContext (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/util/errorContext.ts:29:5)\n    at Observable.subscribe (/workspace/Dev/temp/nest_log/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/src/internal/Observable.ts:221:5)" }, "msg": "Test Error" },
    ]
});

// const ws = new WebSocket("ws://127.0.0.1:8080");
// ws.onmessage = (event: MessageEvent<string>) => {
//     state.logList.push(JSON.parse(event.data));
// };
</script>
<template>
    <el-timeline>
        <LogItem :log-item="item" v-for="item in state.logList" />
    </el-timeline>
</template>
<style>
.list .log-item {
    margin-bottom: 14px;
}
</style>